---
- hosts: local

  vars:
  

  tasks:
  
    - name: Sprawdzanie systemu
      fail: msg="SYSTEM MUSI BYC 64-bitowy"
      when: ansible_architecture != "x86_64"
      
      
    - pause:
        prompt: ENTER
